highlighter: pygments
markdown: KramdownPygments

# For some reason kramdown seems to behave differently on different
# OS/packages wrt encoding. So we hard code this config.
kramdown:
  entity_output: numeric
  input: GFM

include:
  - _static
  - _modules

exclude:
  - README.md
  - build_doc.sh

# These allow the documentation to be updated with newer releases of Gearpump
GEARPUMP_VERSION: 0.8.1-SNAPSHOT
SCALA_BINARY_VERSION: "2.11"
SCALA_VERSION: "2.11.8"
GEARPUMP_ISSUE_TRACKER_URL: https://github.com/gearpump/gearpump/issues
GEARPUMP_GITHUB_URL: https://github.com/gearpump/gearpump
GEARPUMP_EXAMPLES_URL: https://github.com/gearpump/gearpump-examples
